spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cqrs
    username: test
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
file:
  upload-dir: /tmp/uploads